# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2500b2c9e21c7a0543202b260ed64854dcef247ed47b69540e47089fa89e4b4dfe97b80ee479b6b94775080fc84c603e6243f381d16c2d0fa232c91c52e07650

test:
  secret_key_base: 9857f76ec581fc4ec6e70c7a48744f2747176056bef0902d2f441e15e1755b1f8767a7251a2b57efd93e2e0ed112b13df5cf341ea4fd64b3f4c217e185c0f8af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
